### ISSUE TITLE
Data Structure

### ISSUE THREAD

**Issue by andrewMacmurray** [ageuk/companion-app#11]
Define a rough draft of data structure for relevant sections

- [ ] Client
- [ ] Companion
- [ ] Action Todo List
- [ ] Topic -> Prompt -> Action tree

**Comment by katbow** [comment]
@andrewMacmurray [this](http://dev.mysql.com/doc/refman/5.7/en/database-use.html) is a relevant part of the docs for creating and using databases and tables for MySQL once you have it installed. Also if you don't like using command line for interacting with the db, there's [MySQL Workbench](https://www.mysql.com/products/workbench/).

**Comment by rjmk** [comment]
Before we discuss this, is there anything you can add to this issue about what needs to be stored and how it needs to be used? Ideally we'll use our discussion today for clarifying what's been written up.

**Comment by andrewMacmurray** [comment]
@rjmk hey sorry we forgot to link this:

https://github.com/ageuk/companion-app/wiki/Database-requirements

**Comment by rjmk** [comment]
Following our discussion, we're suggesting a data structure something like this.

## SQL
### Companion Table
| ID | Password (hashed) | ... |
| :-:| :-: | :-: |

### Client Table
| ID | Name | CompanionID | Notes | ... |
| :--:| :----: | :---: | :---: | :---: |

* We could use the case ID as the ID of the client; if this may change, we can have a separate database ID and then have the case as a column.
* We are listing a single companion here. Though we think there may be multiple companions over time, or perhaps even at the same time, I think this is a reasonable structure to start with. Not least because we may well desire to know the current and/or main companion, which may not be indicated from a junction table.

### Topics
| ID | Value | ... |
| :-:| :-: | :-: |

### Prompts
| ID | Value | TopicID | ... |
| :-:| :-: | :-: | :-: |

### Questions
| ID | Value | PromptID | ... |
| :-:| :-: | :-: | :-: |

### Actions
| ID | Value | QuestionID | ... |
| :-:| :-: | :-: | :-: |

### Client-Topic Junction
| ID | ClientID | TopicID | 
| :-:| :-: | :-: |

### Client-Question Junction
| ID | ClientID | QuestionID | 
| :-:| :-: | :-: |

### Client-Action Junction
| ID | ClientID | ActionID | 
| :-:| :-: | :-: |

* `Client-Question` and `Client-Action` are tables used to indicate a question has been asked / action has been taken
* **Assumptions**
 * Prompts only belong to one topic; questions only belong to one prompt; actions only belong to one question
 * We only need to store which questions have been completed (for now)
 * We need to store which actions have been completed
 * We need to allow custom / edited topics for a given client -- as we are assuming one companion / client currently, we're not considering the case where different companions have different topics for the same client
    * At the moment, changing the topic allows the most flexibility so this is the approach taken -- it also means we don't need a `client-topic-prompt` junction, or anything like that

## LocalStorage

For now we're suggesting mirroring the structure of the database in JSON. We may well desire to write conversions between the normalised SQL structure and a JSON structure that's easier to work with, but we want to put that on hold until a) we have full wireframes and b) we know what's a pain to work with when the data is in this shape.

Therefore, a given client might have data something like

```js
{ clients:
  [ { id: 2347
    , name: "Anne Onymous"
    , notes: ""
    }
  , { id: 1
    , name: "Miss Terry"
    , notes: "A note"
    }
  ]
, topics:
  [ id: 1
  , value: "1st topic"
  ]
, prompts:
  [ id: 1
  , value: "1st prompt"
  , topicID: 1
  ]
...
client_topics:
  [ id: 1
  , client_id: 1
  , topic: 1
  ]
}
```

Let me know if you have questions, @andrewMacmurray @katbow

**Comment by katbow** [comment]
questions:
for LocalStorage, are the topics, prompts, and client_topics meant to be arrays of objects?

Rather than topics -> prompts -> questions -> actions, there are only 3 layers (without questions). So because of that, should any assumptions about questions be moved to prompts? For example this section :

> * Prompts only belong to one topic; questions only belong to one prompt; actions only belong to one question
> * We only need to store which questions have been completed (for now)

Lastly, when discussing completed actions or actions which have been taken, does this mean actions which have been added to be done? Or for later sprints when actions will be able to be ticked off as complete?

**Comment by rjmk** [comment]
> for LocalStorage, are the topics, prompts, and client_topics meant to be arrays of objects?

Yes! Updated

> Rather than topics -> prompts -> questions -> actions, there are only 3 layers (without questions). So because of that, should any assumptions about questions be moved to prompts?

Yes! Will update

> Lastly, when discussing completed actions or actions which have been taken, does this mean ... for later sprints when actions will be able to be ticked off as complete?

Yes!

**Comment by rjmk** [comment]
* [] Add types to columns
* [] Add boolean 'completed' to `Client-Action`
* [] Remove client-question junctions

**Comment by katbow** [comment]
Moved this to the wiki so it's each to find & this can be closed. [See here.](https://github.com/ageuk/companion-app/wiki/Data-Structure)
