### ISSUE TITLE
Offline id assignment

### ISSUE THREAD

**Issue by rjmk** [ageuk/companion-app#66]
Can companions create custom actions offline? If so, we need to work out how (temporary?) offline ids are assigned.

See also the id proposal [here](https://github.com/ageuk/companion-app/issues/63)

**Comment by katbow** [comment]
We checked this out today, and editability will only be available while they are online. So that includes:
* adding in new clients
* editing topics
* editing prompts
* editing actions

The only thing that will be changed/added in for localStorage (while offline) then is:
* actions added to be completed
* notes for the client
